### ISSUE TITLE
Update the minimum supported PHP version

### ISSUE THREAD

**Issue by dingo-d** [PHPCompatibility/PHPCompatibilityWP#10]
Recently the minimum supported version of WordPress was changed from PHP5.2 to 5.6.

This should be reflected in this repo as well 🙂

**Comment by jrfnl** [comment]
AFAICS, that would only be a documentation update, no code/ruleset changes needed.
Pull requests welcome :smile:

**Comment by paulschreiber** [comment]
This was fixed with #11.
