### ISSUE TITLE
Getting this error : ERROR: Referenced sniff "PHPCompatibilityWP" does not exist  when i am trying to  check woocommerce standard

### ISSUE THREAD

**Issue by abhayp-cedcoss** [PHPCompatibility/PHPCompatibilityWP#19]
Running this command : Desktop/tide-plugin$ phpcs --warning-severity=0 --report=xml --report-file=/home/cedcoss/Desktop/orderbump.xml --ignore-annotations --extensions=php --standard=WooCommerce-Core --ignore=/vendor/ abc.php

then it's showing this error:

ERROR: Referenced sniff "PHPCompatibilityWP" does not exist

Thanks in advance

**Comment by jrfnl** [comment]
@abhayp-cedcoss The simple answer is that [external standards need to be registered](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths) with PHPCS before they can be used.

As I don't know the `WooCommerce-Core` standard and don't know how you've installed PHPCS, I can not give you a more directly applicable answer.

**Comment by jrfnl** [comment]
@abhayp-cedcoss Did you ever get this working ? If not: please provide more information.

**Comment by jrfnl** [comment]
Closing for lack of response. If/when more information is provided, the issue can be re-opened.
