### ISSUE TITLE
Fatal Error: Allowed Memory Size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by metalandcoffee** [PHPCompatibility/PHPCompatibilityWP#25]
Hi there 👋🏾

When I run `phpcs -p wordpress-plugin --standard=PHPCompatibilityWP --runtime-set testVersion 7.3- --extensions=php`, I get the following error:

```
......................W...W............
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /.composer/vendor/squizlabs/php_codesniffer/src/Tokenizers/Tokenizer.php on line 1504
```

The file that it is stopping at (when I add the `-v` flag) is 25,000 lines long. Could this be why?

**Comment by jrfnl** [comment]
Well, yes, that wouldn't surprise me at all. Depending on how complex (and long) the file is, the tokenization can take up quite some memory.

You could try raising the `memory_limit` in the `php.ini` file used by the process.

**Comment by metalandcoffee** [comment]
Thanks @jrfnl - I'll do that. Just wanted to double check :)

**Comment by jrfnl** [comment]
No problem. Hope it fixes the issue for you.

**Comment by vialjoris** [comment]
phpcs -d memory_limit=512M -p wordpress-plugin --standard=PHPCompatibilityWP --runtime-set testVersion 7.3- --extensions=php
