### ISSUE TITLE
Allow use of PHPCompatibilty:dev-develop

### ISSUE THREAD

**Issue by GaryJones** [PHPCompatibility/PHPCompatibilityWP#40]
Installing the master branch / latest release of PHPCompatibilityWP will use PHPCompatibility `^9.0`.

It would be useful to be able to install a (temporary) version of PHPCompatibilityWP that would use the `dev-develop` branch of PHPComapatibility, so that sniffs with some PHP 8 focus can be used.

What's the best way of providing that?
(Either as a new branch here, or instructions in the readme on how users can adapt their project / global install)

**Comment by jrfnl** [comment]
@GaryJones I have a feeling I already answered this for you before ?

Either way, the answer hasn't changed:
```bash
composer config minimum-stability dev
composer require --dev phpcompatibility/php-compatibilitywp
composer require --dev phpcompatibility/php-compatibility:"dev-develop as 9.99.99"
```

The `dev-develop as 9.99.99` aliases the `develop` branch of PHPCompatibility to a `9.x` version which is within the allowed range for PHPCompatibilityWP.

We ourselves use the same principle to already run the tests against PHPCompatibility `dev-develop`:
* https://github.com/PHPCompatibility/PHPCompatibilityWP/blob/79966df2570451119bb6f44952044964f1c8c91b/.github/workflows/ci.yml#L65-L68
* https://github.com/PHPCompatibility/PHPCompatibilityWP/runs/6437683082?check_suite_focus=true

Note: once PHPCompatibility 10.0.0 has come out, this repo will get a 3.0.0 release based on PHPCompatibility 10.0.0.

**Comment by GaryJones** [comment]
I thought you had too, but I couldn't remember it :-)

Thank you!

**Comment by jrfnl** [comment]
@GaryJones No worries. For next time: you can bookmark the thread in Slack: https://a8c.slack.com/archives/C9GD9DSSZ/p1650535294937309
